version: "3.9"
services:
  fullstack:
    build:
      context: .
      dockerfile: Dockerfilemain
    container_name: fullstack
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - postgres
    working_dir: /app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: snekkbank

    command: sh -c " pytest --maxfail=1 --disable-warnings && uvicorn backend.main:app --host 0.0.0.0 --port 5001 --reload"

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: snekkbank
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true" # fixes memory issues sometimes
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  tests-and-sonar:
    build:
      context: backend\\tests
      dockerfile: Dockerfile
    container_name: tests-and-sonar
    working_dir: /app
    environment:
      PYTHONPATH: /app
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: snekkbank
    volumes:
      - .:/app
    depends_on:
      - fullstack
      - sonarqube
    command: tail -f /dev/null



  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # Vite dev server proxy uses this to reach FastAPI inside Docker
      - INTERNAL_API_URL=http://fullstack:5001
volumes:
  pg_data:
